# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               PHPCoder
tagline:             'a coder desire for freedom'
description:         'just do it'
url:                 http://ferdbi.com
baseurl:             /
paginate:            7
suibi:               随笔 
php:                 PHP
Mysql:               Mysql
suanfa:              算法
# About/contact
author:
  name:              conghaoyuan
  url:               https://www.facebook.com/profile.php?id=100009305848329
  email:             conghaoyuan@gmail.com

# Custom vars
version:             2.0

# Search 
search:             google
# Social Media
github:				http://github.com/conghaoyuan
facebook:			https://www.facebook.com/profile.php?id=100009305848329

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
creator:			PHP Coder
codename:			conghaoyuan
