# Dependencies
markdown:            kramdown
#highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               CrazyCoder
tagline:             'To be both a speaker of words and a doer of deeds.'
description:         'just do it   &nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#ffffff">袁从灏</font></b>'
url:                 http://ferdbi.com
baseurl:             /
paginate:            7
suibi:               随笔 
Linux:		           Linux
php:                 PHP
java:	               Java
Mysql:               Mysql
suanfa:              算法
iosmac:	             ios|os x
kuangjia:	           框架
lunwen:		           论文
machine:	           机器学习
bigdata:	     大数据

# About/contact
author:
  name:              conghaoyuan
  url:               https://www.facebook.com/profile.php?id=100009305848329
  email:             conghaoyuan@gmail.com

# Custom vars
version:             2.0

# Search 
search:             google
# Social Media
github:				http://github.com/conghaoyuan
facebook:			https://www.facebook.com/profile.php?id=100009305848329

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
creator:			Crazy Coder
codename:			conghaoyuan
